controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

book_controller:
    resource: '../src/Controller/BookController.php'
    type: annotation
